# --- !Ups
create table "short_link" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "redirect_to_url" varchar unique not null,
  "token" varchar unique not null,
  "expiration_date" date,
  "expired" boolean not null default 0
);

# --- !Downs
drop table "short_link" if exists;
