# --- !Ups
create table "short_link" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "redirect_to_url" varchar not null,
  "token" varchar not null
);

# --- !Downs
drop table "short_link" if exists;
