# --- !Ups
create table "user" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar unique not null,
  "hashed_password" varchar not null
);

# --- !Downs
drop table "user" if exists;
